-- System exercises required by the Hybrid 4-day starter program.
-- Search URLs only: we do not invent specific video IDs that can rot or be wrong.

insert into public.exercises
  (id, owner_id, name, category, measurement, muscle_groups, equipment, instructions, video_url)
values
  ('11111111-1111-4111-8111-111111111215', null, 'Bodyweight Squat', 'strength', 'reps', array['quads', 'glutes'], array['bodyweight'], 'Feet about shoulder-width. Sit between the hips, keep the chest up, and stand by driving the floor away. Knees track over the feet.', 'https://www.youtube.com/results?search_query=Bodyweight%20Squat%20proper%20form'),
  ('11111111-1111-4111-8111-111111111216', null, 'Scapular Push-Up', 'strength', 'reps', array['shoulders', 'upper back', 'core'], array['bodyweight'], 'Start in a high plank with arms straight. Let the chest sink by squeezing the shoulder blades, then push the floor away to spread them. Elbows stay locked.', 'https://www.youtube.com/results?search_query=Scapular%20Push-Up%20proper%20form'),
  ('11111111-1111-4111-8111-111111111217', null, 'External Rotation', 'strength', 'weight_reps', array['rotator cuff', 'shoulders'], array['band', 'cable'], 'Elbow pinned to the side (a small towel between elbow and ribs helps). Rotate the forearm outward, then return slowly. Do not let the elbow drift.', 'https://www.youtube.com/results?search_query=Cable%20External%20Rotation%20rotator%20cuff%20proper%20form'),
  ('11111111-1111-4111-8111-111111111218', null, 'Chest-Supported Dumbbell Row', 'strength', 'weight_reps', array['upper back', 'lats', 'biceps'], array['dumbbells', 'bench'], 'Lie chest-down on an incline bench. Pull the elbows toward the hips, pause, and lower under control. Do not yank with the hands.', 'https://www.youtube.com/results?search_query=Chest%20Supported%20Dumbbell%20Row%20proper%20form'),
  ('11111111-1111-4111-8111-111111111219', null, 'Wrist Extension', 'strength', 'weight_reps', array['forearms'], array['dumbbells'], 'Forearm fully supported, palm down. Extend only the wrist, then lower slowly. The forearm stays still.', 'https://www.youtube.com/results?search_query=Wrist%20Extension%20dumbbell%20proper%20form'),
  ('11111111-1111-4111-8111-111111111220', null, 'Isometric Hammer Curl', 'strength', 'duration', array['biceps', 'forearms'], array['dumbbells'], 'Hold a neutral (hammer) grip with the elbow at about 90 degrees. Strong but pain-free contraction — not a max-effort grind. Log the hold time.', 'https://www.youtube.com/results?search_query=Isometric%20Hammer%20Curl%20proper%20form'),
  ('11111111-1111-4111-8111-111111111221', null, 'Glute Bridge', 'strength', 'reps', array['glutes', 'hamstrings'], array['mat'], 'Lie on your back, feet planted. Drive through the heels until the hips lock out in a straight line from knees to shoulders, then lower with control.', 'https://www.youtube.com/results?search_query=Glute%20Bridge%20proper%20form'),
  ('11111111-1111-4111-8111-111111111222', null, 'Hip Hinge', 'mobility', 'reps', array['hamstrings', 'glutes', 'lower back'], array['none'], 'Soft knees, push the hips back while keeping a long spine. Feel the hamstrings load, then stand tall by driving the hips forward. This is not a squat.', 'https://www.youtube.com/results?search_query=Hip%20Hinge%20proper%20form'),
  ('11111111-1111-4111-8111-111111111223', null, 'Kettlebell Deadlift', 'strength', 'weight_reps', array['glutes', 'hamstrings', 'back'], array['kettlebell'], 'Bell between the feet. Hinge, grab the horns, brace, and stand tall by pushing the floor away. Lower with the same hinge.', 'https://www.youtube.com/results?search_query=Kettlebell%20Deadlift%20proper%20form'),
  ('11111111-1111-4111-8111-111111111224', null, 'Single-Leg Romanian Deadlift', 'strength', 'weight_reps', array['hamstrings', 'glutes', 'core'], array['dumbbells'], 'Hinge on one leg, hips square, standing knee soft. The free leg reaches back. Weight is secondary to balance and pelvic control.', 'https://www.youtube.com/results?search_query=Single%20Leg%20Romanian%20Deadlift%20proper%20form'),
  ('11111111-1111-4111-8111-111111111225', null, 'Half-Kneeling One-Arm Cable Press', 'strength', 'weight_reps', array['chest', 'shoulders', 'core'], array['cable'], 'Half-kneeling, opposite arm pressing. Squeeze the down-knee glute, ribs down, and press without letting the cable rotate the torso.', 'https://www.youtube.com/results?search_query=Half%20Kneeling%20One%20Arm%20Cable%20Press%20proper%20form'),
  ('11111111-1111-4111-8111-111111111226', null, 'Step-Up', 'strength', 'weight_reps', array['quads', 'glutes'], array['box', 'dumbbells'], 'Box high enough that the working thigh is about parallel. Drive through the front foot — do not push off the back leg. Stand tall, then lower with control.', 'https://www.youtube.com/results?search_query=Step-Up%20exercise%20proper%20form'),
  ('11111111-1111-4111-8111-111111111227', null, 'Suitcase Carry', 'strength', 'duration', array['core', 'obliques', 'forearms'], array['dumbbells', 'kettlebells'], 'One heavy bell at the side. Walk tall without leaning toward or away from the weight. Short stable steps. Log the loaded walking time.', 'https://www.youtube.com/results?search_query=Suitcase%20Carry%20proper%20form'),
  ('11111111-1111-4111-8111-111111111228', null, 'Pallof Press', 'strength', 'weight_reps', array['core', 'obliques'], array['cable'], 'Stand side-on to the cable, press the handle straight out, and hold. Do not let the stack rotate you. Return to the chest and repeat.', 'https://www.youtube.com/results?search_query=Pallof%20Press%20proper%20form'),
  ('11111111-1111-4111-8111-111111111229', null, 'Dead Bug', 'strength', 'reps', array['abs', 'core'], array['mat'], 'Low back stays on the floor. Exhale as you reach the opposite arm and leg. If the back peels up, shorten the range.', 'https://www.youtube.com/results?search_query=Dead%20Bug%20proper%20form'),
  ('11111111-1111-4111-8111-111111111230', null, 'Scaption Raise', 'strength', 'weight_reps', array['shoulders', 'rotator cuff'], array['dumbbells'], 'Very light bells. Raise the arms 30–45 degrees forward of the side plane, thumbs up, to about shoulder height. No swinging.', 'https://www.youtube.com/results?search_query=Scaption%20Raise%20proper%20form'),
  ('11111111-1111-4111-8111-111111111231', null, 'Wrist Pronation/Supination', 'strength', 'weight_reps', array['forearms'], array['dumbbells'], 'Elbow at 90 degrees, forearm supported. Hold a light dumbbell by one end and rotate only the forearm both ways. Very light to start.', 'https://www.youtube.com/results?search_query=Wrist%20Pronation%20Supination%20dumbbell%20proper%20form')
on conflict (id) do update
  set name = excluded.name,
      category = excluded.category,
      measurement = excluded.measurement,
      muscle_groups = excluded.muscle_groups,
      equipment = excluded.equipment,
      instructions = excluded.instructions,
      video_url = excluded.video_url;
